added dummy images and edited howitworks bg  color
Paulette-Zaldivar-Flores/Friendster pull request #24
Opened 2023-11-15 03:22 UTC by srollins01

https://paulette-thedev.atlassian.net/browse/EP-22

2023-11-15 11:26 UTC, Paulette-Zaldivar-Flores reviewed
@srollins01 looks great but would you mind making the image responsive?

Uploading Screen Recording 2566-11-15 at 20.23.50.mov…

2023-11-16 14:58 UTC, srollins01 commented
Hi @Paulette-Zaldivar-Flores, I fixed the images and made some other adjustments. Please have a look at the second commit.

2023-11-17 10:03 UTC, Paulette-Zaldivar-Flores requested changes
@srollins01 most images look good on desktop however the images on mobile are still cut off. Since we are using Bootstrap maybe placing them in a card might make responsiveness easier?

2023-11-17 10:48 UTC, Paulette-Zaldivar-Flores approved these changes

2023-11-17 10:49 UTC, merged