Added sign-up page
Paulette-Zaldivar-Flores/Friendster pull request #39
Opened 2024-04-02 11:15 UTC by srollins01

Created sign-up route and page with Firebase authentication.

2024-04-24 06:57 UTC, srollins01 commented on friendster-frontend/vite-project/src/components/Login.jsx
> +        const expirationTime = new Date().getTime() + 30*10 * 1000;//
It looks like the token expiration time is set to 5 minutes. I believe you said you wanted to set it to 30 minutes?

2024-04-24 06:59 UTC, srollins01 commented
@amante739 Thanks for fixing the sign-up issues. I've rebased our commits with the master branch and made some adjustments + left feedback. Please have a look when you have time.

2024-04-24 07:52 UTC, Paulette-Zaldivar-Flores requested changes
@srollins01 @amante739 I tested the sign up function but could not get past this screen telling me there is a problem with sign up and it does not tell me what the problem is. I did an npm beforehand to make sure axios was installed. Is there anything else I should be doing when testing this?
<img width="1417" alt="Screenshot 2567-04-24 at 16 49 14" src="https://github.com/Paulette-Zaldivar-Flores/Friendster/assets/96970580/33e37cd5-55ba-47d2-aa42-54e850b9bc2b">

2024-04-29 11:12 UTC, Paulette-Zaldivar-Flores commented
@srollins01 @amante739 I tested the sign up feature and get this  500 error coming from axios. Not sure what the problem since I did npm i on both frontend and backend. Check it out.

https://github.com/Paulette-Zaldivar-Flores/Friendster/assets/96970580/0a83044b-5e97-47b5-a6bb-fae69ce649f9

2024-07-06 15:25 UTC, merged